# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Welcome linux folks
email:
classes: wide
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Calcutta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ashokkrishna"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Passionate Linux enthusiast and cybersecurity professional focused on threat intelligence, DFIR, and system security."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://linuxsecurity.in"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/ashokkrishna99"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/le0li9ht"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ashok-krishna-vemuri/"

atom_feed:
  path                   : # blank (default) uses feed.xml
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google

# Reading Files

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: home
      author_profile: true
      read_time: true
      comments: true
      share: true
      show_date: true
      related: true
      enable_copy_code_button: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification : "918dpNsUEDjoEgVVRTvIrg5DhcVaQdQwFc54qLwDQHI"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  : 

#bing_site_verification: "F72197164CCB51EF9818C9E4A07EE9DD"
# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "G-4CL31GFWX5"
    anonymize_ip         : # true, false (default)
footer:
  links:
  copyright:
    enabled: true
    powered_by: true
